const assert = require("assert");
const fs = require("fs");
const path = require("path");
const read = file => fs.readFileSync(path.join(__dirname, "..", file), "utf8");
const popup = read("src/ui/popup.html");
const popupLogic = read("src/ui/popup.js");
const background = read("src/recorder/background.js");
const report = read("src/ui/technical-report.html");
const reportLogic = read("src/ui/technical-report.js");
const reportView = read("src/ui/technical-report-workspace-view.js");

assert.match(popup, /id="startProcess"/);
assert.match(popup, /id="startBug"/);
assert.match(popup, /Dokumentera en process/);
assert.match(popup, /Rapportera ett fel/);
assert.match(popupLogic, /T9_START_BUG_RECORDING/);
assert.match(popupLogic, /Felrapportering pågår/);
assert.match(popupLogic, /Business Central-felet.*fångats/);
assert.match(popupLogic, /T9_FINISH_BUG_RECORDING/);
assert.match(popup, /id="nameDialog"/);
assert.match(popup, /id="cancelName"[^>]*>Avbryt<\/button>/);
assert.doesNotMatch(popup, /id="cancelName"[^>]*>Fortsätt spela in<\/button>/);
assert.match(popup, /id="discardRecording"[^>]*>Avbryt inspelning<\/button>/);
assert.match(popupLogic, /type: "T9_CANCEL_RECORDING"/);
assert.match(popupLogic, /Alla registrerade händelser och bilder i den tas bort/);
assert.match(background, /case "T9_CANCEL_RECORDING"/);
assert.match(background, /await cancelActiveSession\(\)/);
assert.match(background, /BC_ERROR_EVIDENCE_PREFIX \+ id/);
assert.match(popup, /id="recordingName" required/);
assert.match(popupLogic, /nameDialog.*showModal/);
assert.match(popupLogic, /finishRecording\(name\)/);
assert.match(background, /stopSession\(message\.name\)/);
assert.match(background, /createAndOpenBugReport\(session\.id, message\.name\)/);
assert.match(background, /createAndOpenBugReport\(session\.id, message\.name\)/);
assert.match(background, /technical-report\.html\?bugReportId=.*new=1/);
assert.match(background, /Reported Business Central problem/);
assert.match(report, /Application Insights \(optional\)/);
assert.match(report, /AI technical analysis \(optional\)/);
assert.match(report, /Issue Package Preview/);
assert.match(reportView, /Technical details/);
assert.match(reportView, /advancedKinds/);
assert.match(reportView, /Captured Business Central error/);
assert.match(reportView, /Copy Business Central error/);
assert.match(reportView, /Ready to share/);
assert.match(reportLogic, /technical-report-expectedResult/);
assert.match(reportLogic, /firstMissing\?\.focus/);
assert.match(report, /id="closeReport"/);
assert.match(reportLogic, /closeReport.*addEventListener[\s\S]*window\.close\(\)/);
const dashboard = read("src/ui/dashboard.js");
assert.match(dashboard, /recordingPurpose:\s*session\.recordingPurpose/);
assert.match(dashboard, /T9_OPEN_TECHNICAL_REPORT/);
assert.match(dashboard, /bugReportId:\s*`bug-report:\$\{session\.id\}`/);
assert.match(report, /@media\(max-width:700px\)/);
assert.match(popupLogic, /recordingPurpose === "bug-report" \? "T9_START_BUG_RECORDING" : "T9_START"/);
console.log("Bug Reporting UX tests passed.");
