const assert = require("assert");
const fs = require("fs");
const path = require("path");
const read = file => fs.readFileSync(path.join(__dirname, "..", file), "utf8");
const popup = read("src/ui/popup.html");
const popupLogic = read("src/ui/popup.js");
const uiTranslations = read("src/ui/i18n.js");
const background = read("src/recorder/background.js");
const reportService = read("src/bug-report/bug-report-service.js");
const report = read("src/ui/technical-report.html");
const reportLogic = read("src/ui/technical-report.js");
const reportView = read("src/ui/technical-report-workspace-view.js");

assert.match(popup, /id="startProcess"/);
assert.match(popup, /id="startBug"/);
assert.match(popup, /Dokumentera en process/);
assert.match(popup, /Rapportera ett fel/);
assert.match(popupLogic, /T9_START_BUG_RECORDING/);
assert.match(popupLogic, /recorder\.bugActive/);
assert.match(uiTranslations, /"recorder\.bugActive": "Felrapportering pågår"/);
assert.match(popupLogic, /recorder\.errorDetailsCaptured/);
assert.match(uiTranslations, /Business Central-felet.*fångats/);
assert.match(popupLogic, /T9_FINISH_BUG_RECORDING/);
assert.match(popupLogic, /function finishOrNameRecording\(state\)/);
assert.match(popupLogic, /recordingPurpose === "bug-report"[\s\S]*finishRecording\("", defaultDocumentLanguage\)/);
assert.match(popupLogic, /else openProcessNameDialog\(\)/);
assert.match(popup, /id="nameDialog"/);
assert.match(popup,
  /id="cancelName"[^>]*[\s\S]*?>Fortsätt spela in<\/button>/);
assert.match(popup,
  /id="discardRecording"[^>]*[\s\S]*?>Ta bort inspelningen<\/button>/);
assert.match(popupLogic, /type: "T9_CANCEL_RECORDING"/);
assert.match(popupLogic, /okänt meddelande/);
assert.match(popupLogic, /discardWithLegacyBackground\(\)/);
assert.match(popupLogic, /type: "T9_STOP"/);
assert.match(popupLogic, /type: "T9_DELETE_SESSION"/);
assert.match(popupLogic, /recorder\.discardConfirm/);
assert.match(uiTranslations, /Alla registrerade händelser och bilder i den tas bort/);
assert.match(background, /case "T9_CANCEL_RECORDING"/);
assert.match(background, /await cancelActiveSession\(\)/);
assert.match(background, /BC_ERROR_EVIDENCE_PREFIX \+ id/);
assert.match(popup, /id="recordingName" required/);
assert.match(popup, /class="name-fields"[\s\S]*class="name-field"[\s\S]*id="recordingName"[\s\S]*class="name-field"[\s\S]*id="recordingDocumentLanguage"/);
assert.match(popup, /input,textarea,select\{width:100%/);
assert.match(popupLogic, /nameDialog.*showModal/);
assert.match(popup, /id="recordingDocumentLanguage"[\s\S]*value="sv-SE"[\s\S]*value="en-US"/);
assert.match(popupLogic, /finishRecording\(name, \$\("recordingDocumentLanguage"\)\.value\)/);
assert.match(background, /stopSession\(message\.name, message\.documentLanguage\)/);
assert.match(background, /setDocumentLanguage\(state\.sessionId,[\s\S]*T9LanguageRegistry\.normalize\(documentLanguage, "document"\)/);
assert.match(background, /createAndOpenBugReport\(session\.id, message\.name\)/);
assert.match(background, /createAndOpenBugReport\(session\.id, message\.name\)/);
assert.match(background, /technical-report\.html\?bugReportId=.*new=1/);
assert.match(reportService, /Reported Business Central problem/);
assert.match(reportService, /Rapporterat problem i Business Central/);
assert.match(report, /Application Insights \(optional\)/);
assert.match(report, /AI technical analysis \(optional\)/);
assert.match(report, /class="primary-actions"[\s\S]*id="openIssuePreview"[\s\S]*id="closeReport"/);
assert.doesNotMatch(report, /id="saveReport"/);
assert.match(report, /<details class="report-options"><summary>More options<\/summary>/);
assert.doesNotMatch(report, /<details class="report-options" open/);
assert.match(report, /Share bug report/);
assert.match(report, /id="openIssuePreview"[^>]*>Share report<\/button>/);
assert.match(report, /<details class="share-options"><summary>Content and settings<\/summary>/);
assert.match(report, /id="issueIncludeTechnical"/);
assert.doesNotMatch(report, /id="issueIncludeTechnical"[^>]*checked/);
assert.match(report, /<details class="share-preview"><summary>Review report content<\/summary>/);
assert.match(report, /class="share-preview"[\s\S]*id="copyIssueDescription"/);
assert.match(report, /id="adoConfiguration"/);
assert.match(report, /id="githubConfiguration"/);
assert.match(report, /id="shareReport"[^>]*>Download report package<\/button>/);
assert.doesNotMatch(report, /id="refreshIssuePreview"/);
assert.doesNotMatch(report, /id="downloadIssuePackage"/);
assert.doesNotMatch(report, /id="submitExternalIssue"/);
assert.match(reportView, /Technical details/);
assert.match(reportView, /advancedKinds/);
assert.match(reportView, /`report-section report-section-\$\{section\.kind\}`/);
assert.match(report, /\.report-section\{[^}]*border-top:/);
assert.match(reportView, /className = "report-core-fields"/);
assert.match(reportView, /className = "report-more-fields"/);
assert.match(reportView, /ui\("Describe the problem", locale\)/);
assert.doesNotMatch(reportView, /moreFields\.open\s*=/);
assert.match(reportView, /failurePoint/);
assert.match(reportView, /className = "reproduction-editor"/);
assert.match(reportView, /Include in report/);
assert.match(reportView, /Use generated text/);
assert.match(reportView, /event\.key === "Enter"/);
assert.match(reportView, /resetInstruction: true/);
assert.match(reportView, /workspaceState\.report\.reproduction/);
assert.match(reportLogic, /workspace\.updateReproductionStep\(id, patch\)/);
assert.match(reportLogic, /const persistentDisclosures =/);
assert.match(reportLogic, /container\.querySelector\(selector\)\?\.open/);
assert.match(reportLogic, /disclosure\.open = true/);
assert.match(reportView, /editorDuplicateKinds/);
assert.match(reportView, /"errors"/);
assert.match(reportView, /const hasCapturedError = Boolean/);
assert.match(reportView, /Additional description/);
assert.match(reportView, /appendScreenshot\(node, primary, "primary-evidence"\)/);
assert.match(reportView, /Screenshot for step/);
assert.match(reportView, /const stepByAsset = new Map/);
assert.match(reportView, /className = "screenshot-editor"/);
assert.match(reportLogic, /workspace\.updateScreenshotVisibility/);
assert.match(reportView, /className = "additional-evidence"/);
assert.match(reportView, /issue\.level === "required"/);
assert.doesNotMatch(reportView, /Complete the required human context below/);
assert.match(reportView, /Captured Business Central error/);
assert.match(reportView, /Copy Business Central error/);
assert.match(reportView, /section\.content\.userDescription, "human-actual-result"/);
assert.match(reportView, /Needs attention/);
assert.doesNotMatch(reportView, /Ready to share/);
assert.match(reportLogic, /technical-report-expectedResult/);
assert.match(reportLogic, /firstMissing\?\.focus/);
assert.match(reportLogic, /function updateShareUi\(\)/);
assert.match(reportLogic, /provider !== "azure-devops"/);
assert.match(reportLogic, /provider !== "github"/);
assert.match(reportLogic, /function downloadOfflinePackage\(\)/);
assert.match(reportLogic, /function submitExternalIssue\(\)/);
assert.match(reportLogic, /const renderAndAutosave = state =>/);
assert.match(reportLogic, /setTimeout\(\(\) => workspace\.save\(\)/);
assert.match(reportLogic, /await workspace\.flush\(\); window\.close\(\)/);
assert.match(report, /id="closeReport"/);
assert.match(reportLogic, /closeReport.*addEventListener[\s\S]*window\.close\(\)/);
const dashboard = read("src/ui/dashboard.js");
assert.match(dashboard, /recordingPurpose:\s*session\.recordingPurpose/);
assert.match(dashboard, /T9_OPEN_TECHNICAL_REPORT/);
assert.match(dashboard, /bugReportId:\s*`bug-report:\$\{session\.id\}`/);
assert.match(report, /@media\(max-width:700px\)/);
assert.match(popupLogic, /recordingPurpose === "bug-report" \? "T9_START_BUG_RECORDING" : "T9_START"/);
console.log("Bug Reporting UX tests passed.");
