const assert = require("assert");
const recording = require("../src/engine/canonical-recording");
const session = { id: "recording-1", name: "Create order", purpose: "process", startedAt: "2026-08-10T08:00:00.000Z", completedAt: null, updatedAt: "2026-08-10T08:00:00.000Z", status: "recording", settings: { environmentName: "Sandbox" } };
const created = recording.create({ id: session.id, legacySession: session });
assert.strictEqual(created.schemaVersion, 1);
assert.strictEqual(created.metadata.businessCentral.environment, "Sandbox");
const raw = { eventNo: 1, timestamp: "2026-08-10T08:01:00.000Z", type: "field-change", fieldName: "Customer No.", value: "10000", futureCaptureProperty: { retained: true } };
const withEvent = recording.addEvent(created, raw);
const withAsset = recording.addScreenshot(withEvent, 1, "data:image/png;base64,abc", "2026-08-10T08:01:01.000Z");
const loaded = recording.normalize(JSON.parse(JSON.stringify(withAsset)));
assert.strictEqual(loaded.events[0].type, "fieldChanged");
assert.deepStrictEqual(loaded.events[0].raw.futureCaptureProperty, { retained: true });
assert.strictEqual(loaded.events[0].screenshotAssetId, loaded.assets[0].id);
assert.strictEqual(loaded.assets[0].mimeType, "image/png");
assert.strictEqual(loaded.schemaVersion, 1);
assert.deepStrictEqual(recording.legacyView(loaded).events, [raw]);
assert.strictEqual(created.events.length, 0);
const old = recording.normalize(null, { session, events: [raw], screenshots: { 1: "data:image/png;base64,abc" } });
assert.strictEqual(old.schemaVersion, 1);
assert.strictEqual(old.events[0].screenshotAssetId, old.assets[0].id);
assert.deepStrictEqual(recording.legacyView(old).events, [raw]);
console.log("Canonical recording tests passed.");
