const assert=require('node:assert/strict');
const path=require('node:path');
const modulePath=path.join(__dirname,'../src/engine/feature-flags.js');
delete global.BC_PROCESS_STUDIO_FEATURE_FLAGS;
delete require.cache[require.resolve(modulePath)];
let flags=require(modulePath);
assert.equal(flags.isEnabled('processIntelligence'),false);
const elements=[{dataset:{feature:'processIntelligence'},hidden:false},{dataset:{feature:'unknown'},hidden:false}];
flags.apply({querySelectorAll:()=>elements});
assert.ok(elements.every(item=>item.hidden));
global.BC_PROCESS_STUDIO_FEATURE_FLAGS={processIntelligence:true};
delete require.cache[require.resolve(modulePath)];
flags=require(modulePath);
assert.equal(flags.isEnabled('processIntelligence'),true);
flags.apply({querySelectorAll:()=>elements});
assert.equal(elements[0].hidden,false);
assert.equal(elements[1].hidden,true);
delete global.BC_PROCESS_STUDIO_FEATURE_FLAGS;
const fs=require('node:fs');
const html=fs.readFileSync(path.join(__dirname,'../src/ui/dashboard.html'),'utf8');
const js=fs.readFileSync(path.join(__dirname,'../src/ui/dashboard.js'),'utf8');
assert.match(html,/id="openProcessAnalysis"[^>]+data-feature="processIntelligence"[^>]+hidden/);
assert.match(html,/id="processOverviewDisclosure"[^>]+data-feature="processIntelligence"[^>]+hidden/);
assert.ok(js.includes('if (!processIntelligenceEnabled()) return;'));
console.log('Process intelligence feature flag tests passed.');
